RobotSpin:
  measure: progress
  thresholds: [0.025 , 0.03, 0.1, 0.15, 0.2, 0.5, 0.7]
  min_lesson_length: 100
  signal_smoothing: true
  parameters:
    spawn_angle_max: [10.0, 15.0, 25.0, 35.0, 45.0, 60.0, 90.0, 120.0]