default:
    trainer: sac
    batch_size: 128
    buffer_size: 50000
    buffer_init_steps: 0
    hidden_units: 128
    init_entcoef: 1.0
    learning_rate: 3.0e-4
    learning_rate_schedule: constant
    max_steps: 5.0e5
    memory_size: 128
    normalize: false
    num_update: 1
    train_interval: 1
    num_layers: 2
    steps_per_update: 3
    time_horizon: 64
    sequence_length: 64
    summary_freq: 10000
    tau: 0.005
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.90

RobotSpin:
    normalize: true 
    batch_size: 512
    max_steps: 5.0e5
    learning_rate: 5.0e-4
    hidden_units: 64
    steps_per_update: 9 # Recommended to be equal to number of agents

    use_recurrent: true 
    memory_size: 16 

    time_horizon: 64 
    buffer_init_steps: 5000

RobotSpinSingle:
    normalize: true 
    max_steps: 5.0e5
    learning_rate: 5.0e-4
    hidden_units: 64

    use_recurrent: true 
    memory_size: 32

    time_horizon: 64 
    buffer_init_steps: 2000